In [2]:
import numpy as np

In [4]:
# question 1
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
b = a.reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
# question 2
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a[(a%2==1)] = -1
print(a)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [6]:
#question 3
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
res1 = np.where(x>y)
print(res1)
res2 = np.where(x==y)
print(res2)

(array([1, 2, 4, 5, 6, 7, 8, 9]),)
(array([0]),)


In [7]:
# question 4
a = np.arange(100).reshape(5,-1)
print(a[:,0:5])

[[ 0  1  2  3  4]
 [20 21 22 23 24]
 [40 41 42 43 44]
 [60 61 62 63 64]
 [80 81 82 83 84]]


In [9]:
# additional question 1
a = np.random.randint(30,41,size=10)
print(a)

[35 35 34 35 31 32 39 31 39 32]


In [10]:
# additional question 2
a = np.array(((1,2,3),(4,5,6),(7,8,10)))
b = np.array(((7,8,10),(4,5,6),(1,2,3)))
c = a+b
e = a-b
print(c)
print(e)
print(a.sum())
print(b.sum(axis=0))
print(c.sum(axis=1))
d = a.dot(b)
print(d)
print(np.sort(c))
print(e.transpose())

[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]
[[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]]
46
[12 15 19]
[31 30 31]
[[ 18  24  31]
 [ 54  69  88]
 [ 91 116 148]]
[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]
[[-6  0  6]
 [-6  0  6]
 [-7  0  7]]
